#############################################################################
# Makefile for building: bin/qfm
# Generated by qmake (2.01a) (Qt 4.7.0) on: Mon Sep 20 22:14:53 2010
# Project:  qfm.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qfm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Imoc -Isrc/ui
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lQtGui -L/usr/lib/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/core/qfmcore.cpp \
		src/main.cpp \
		src/qfm.cpp \
		src/listitem.cpp moc/moc_qfmcore.cpp \
		moc/moc_qfm.cpp \
		moc/moc_listitem.cpp
OBJECTS       = obj/qfmcore.o \
		obj/main.o \
		obj/qfm.o \
		obj/listitem.o \
		obj/moc_qfmcore.o \
		obj/moc_qfm.o \
		obj/moc_listitem.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		qfm.pro
QMAKE_TARGET  = qfm
DESTDIR       = bin/
TARGET        = bin/qfm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui/ui_mainwin.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qfm.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtCore.prl
	$(QMAKE) -o Makefile qfm.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qfm.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/qfm1.0.0 || $(MKDIR) obj/qfm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/qfm1.0.0/ && $(COPY_FILE) --parents src/interfaces/commandbuffer.h src/core/qfmcore.h src/qfm.h src/listitem.h obj/qfm1.0.0/ && $(COPY_FILE) --parents src/core/qfmcore.cpp src/main.cpp src/qfm.cpp src/listitem.cpp obj/qfm1.0.0/ && $(COPY_FILE) --parents src/ui/mainwin.ui obj/qfm1.0.0/ && (cd `dirname obj/qfm1.0.0` && $(TAR) qfm1.0.0.tar qfm1.0.0 && $(COMPRESS) qfm1.0.0.tar) && $(MOVE) `dirname obj/qfm1.0.0`/qfm1.0.0.tar.gz . && $(DEL_FILE) -r obj/qfm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_qfmcore.cpp moc/moc_qfm.cpp moc/moc_listitem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_qfmcore.cpp moc/moc_qfm.cpp moc/moc_listitem.cpp
moc/moc_qfmcore.cpp: src/core/qfmcore.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/core/qfmcore.h -o moc/moc_qfmcore.cpp

moc/moc_qfm.cpp: src/core/qfmcore.h \
		src/ui/ui_mainwin.h \
		src/qfm.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/qfm.h -o moc/moc_qfm.cpp

moc/moc_listitem.cpp: src/listitem.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/listitem.h -o moc/moc_listitem.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui/ui_mainwin.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui/ui_mainwin.h
src/ui/ui_mainwin.h: src/ui/mainwin.ui
	/usr/bin/uic src/ui/mainwin.ui -o src/ui/ui_mainwin.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/qfmcore.o: src/core/qfmcore.cpp src/core/qfmcore.h \
		src/qfm.h \
		src/ui/ui_mainwin.h \
		src/interfaces/commandbuffer.h \
		src/listitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qfmcore.o src/core/qfmcore.cpp

obj/main.o: src/main.cpp src/qfm.h \
		src/core/qfmcore.h \
		src/ui/ui_mainwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/qfm.o: src/qfm.cpp src/qfm.h \
		src/core/qfmcore.h \
		src/ui/ui_mainwin.h \
		src/listitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qfm.o src/qfm.cpp

obj/listitem.o: src/listitem.cpp src/listitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/listitem.o src/listitem.cpp

obj/moc_qfmcore.o: moc/moc_qfmcore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qfmcore.o moc/moc_qfmcore.cpp

obj/moc_qfm.o: moc/moc_qfm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qfm.o moc/moc_qfm.cpp

obj/moc_listitem.o: moc/moc_listitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_listitem.o moc/moc_listitem.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

